/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as EditingRouteImport } from './routes/editing'
import { Route as ApiAiAssistantRouteImport } from './routes/api.ai-assistant'
import { Route as ApiCommentsRouteImport } from './routes/api.comments'
import { Route as ApiEnquiriesRouteImport } from './routes/api.enquiries'
import { Route as ApiFeaturedProjectsRouteImport } from './routes/api.featured-projects'
import { Route as ApiGoogleDriveRouteImport } from './routes/api.google-drive'
import { Route as ApiHomepageContentRouteImport } from './routes/api.homepage-content'
import { Route as ApiResumeRouteImport } from './routes/api.resume'
import { Route as ApiSeoSettingsRouteImport } from './routes/api.seo-settings'
import { Route as ApiShowreelRouteImport } from './routes/api.showreel'
import { Route as ApiSiteImagesRouteImport } from './routes/api.site-images'
import { Route as ApiSocialLinksRouteImport } from './routes/api.social-links'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ApiAdminLoginRouteImport } from './routes/api.admin.login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api.admin.logout'
import { Route as ApiAdminVerifyRouteImport } from './routes/api.admin.verify'
import { Route as ApiProjectsIndexRouteImport } from './routes/api.projects.index'
import { Route as ApiProjectsIdRouteImport } from './routes/api.projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const EditingRoute = EditingRouteImport.update({
  id: '/editing',
  path: '/editing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAssistantRoute = ApiAiAssistantRouteImport.update({
  id: '/api/ai-assistant',
  path: '/api/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnquiriesRoute = ApiEnquiriesRouteImport.update({
  id: '/api/enquiries',
  path: '/api/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeaturedProjectsRoute = ApiFeaturedProjectsRouteImport.update({
  id: '/api/featured-projects',
  path: '/api/featured-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleDriveRoute = ApiGoogleDriveRouteImport.update({
  id: '/api/google-drive',
  path: '/api/google-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHomepageContentRoute = ApiHomepageContentRouteImport.update({
  id: '/api/homepage-content',
  path: '/api/homepage-content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeRoute = ApiResumeRouteImport.update({
  id: '/api/resume',
  path: '/api/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoSettingsRoute = ApiSeoSettingsRouteImport.update({
  id: '/api/seo-settings',
  path: '/api/seo-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShowreelRoute = ApiShowreelRouteImport.update({
  id: '/api/showreel',
  path: '/api/showreel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteImagesRoute = ApiSiteImagesRouteImport.update({
  id: '/api/site-images',
  path: '/api/site-images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialLinksRoute = ApiSocialLinksRouteImport.update({
  id: '/api/social-links',
  path: '/api/social-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVerifyRoute = ApiAdminVerifyRouteImport.update({
  id: '/api/admin/verify',
  path: '/api/admin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIndexRoute = ApiProjectsIndexRouteImport.update({
  id: '/api/projects/',
  path: '/api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/api/projects/$id',
  path: '/api/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/editing': typeof EditingRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/api/featured-projects': typeof ApiFeaturedProjectsRoute
  '/api/google-drive': typeof ApiGoogleDriveRoute
  '/api/homepage-content': typeof ApiHomepageContentRoute
  '/api/resume': typeof ApiResumeRoute
  '/api/seo-settings': typeof ApiSeoSettingsRoute
  '/api/showreel': typeof ApiShowreelRoute
  '/api/site-images': typeof ApiSiteImagesRoute
  '/api/social-links': typeof ApiSocialLinksRoute
  '/api/upload': typeof ApiUploadRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/verify': typeof ApiAdminVerifyRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/editing': typeof EditingRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/api/featured-projects': typeof ApiFeaturedProjectsRoute
  '/api/google-drive': typeof ApiGoogleDriveRoute
  '/api/homepage-content': typeof ApiHomepageContentRoute
  '/api/resume': typeof ApiResumeRoute
  '/api/seo-settings': typeof ApiSeoSettingsRoute
  '/api/showreel': typeof ApiShowreelRoute
  '/api/site-images': typeof ApiSiteImagesRoute
  '/api/social-links': typeof ApiSocialLinksRoute
  '/api/upload': typeof ApiUploadRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/verify': typeof ApiAdminVerifyRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/projects': typeof ApiProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/editing': typeof EditingRoute
  '/api/ai-assistant': typeof ApiAiAssistantRoute
  '/api/comments': typeof ApiCommentsRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/api/featured-projects': typeof ApiFeaturedProjectsRoute
  '/api/google-drive': typeof ApiGoogleDriveRoute
  '/api/homepage-content': typeof ApiHomepageContentRoute
  '/api/resume': typeof ApiResumeRoute
  '/api/seo-settings': typeof ApiSeoSettingsRoute
  '/api/showreel': typeof ApiShowreelRoute
  '/api/site-images': typeof ApiSiteImagesRoute
  '/api/social-links': typeof ApiSocialLinksRoute
  '/api/upload': typeof ApiUploadRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/verify': typeof ApiAdminVerifyRoute
  '/api/projects/$id': typeof ApiProjectsIdRoute
  '/api/projects/': typeof ApiProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/digital-marketing'
    | '/editing'
    | '/api/ai-assistant'
    | '/api/comments'
    | '/api/enquiries'
    | '/api/featured-projects'
    | '/api/google-drive'
    | '/api/homepage-content'
    | '/api/resume'
    | '/api/seo-settings'
    | '/api/showreel'
    | '/api/site-images'
    | '/api/social-links'
    | '/api/upload'
    | '/portfolio/$slug'
    | '/portfolio/'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/verify'
    | '/api/projects/$id'
    | '/api/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/digital-marketing'
    | '/editing'
    | '/api/ai-assistant'
    | '/api/comments'
    | '/api/enquiries'
    | '/api/featured-projects'
    | '/api/google-drive'
    | '/api/homepage-content'
    | '/api/resume'
    | '/api/seo-settings'
    | '/api/showreel'
    | '/api/site-images'
    | '/api/social-links'
    | '/api/upload'
    | '/portfolio/$slug'
    | '/portfolio'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/verify'
    | '/api/projects/$id'
    | '/api/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/digital-marketing'
    | '/editing'
    | '/api/ai-assistant'
    | '/api/comments'
    | '/api/enquiries'
    | '/api/featured-projects'
    | '/api/google-drive'
    | '/api/homepage-content'
    | '/api/resume'
    | '/api/seo-settings'
    | '/api/showreel'
    | '/api/site-images'
    | '/api/social-links'
    | '/api/upload'
    | '/portfolio/$slug'
    | '/portfolio/'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/verify'
    | '/api/projects/$id'
    | '/api/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  EditingRoute: typeof EditingRoute
  ApiAiAssistantRoute: typeof ApiAiAssistantRoute
  ApiCommentsRoute: typeof ApiCommentsRoute
  ApiEnquiriesRoute: typeof ApiEnquiriesRoute
  ApiFeaturedProjectsRoute: typeof ApiFeaturedProjectsRoute
  ApiGoogleDriveRoute: typeof ApiGoogleDriveRoute
  ApiHomepageContentRoute: typeof ApiHomepageContentRoute
  ApiResumeRoute: typeof ApiResumeRoute
  ApiSeoSettingsRoute: typeof ApiSeoSettingsRoute
  ApiShowreelRoute: typeof ApiShowreelRoute
  ApiSiteImagesRoute: typeof ApiSiteImagesRoute
  ApiSocialLinksRoute: typeof ApiSocialLinksRoute
  ApiUploadRoute: typeof ApiUploadRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminVerifyRoute: typeof ApiAdminVerifyRoute
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
  ApiProjectsIndexRoute: typeof ApiProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editing': {
      id: '/editing'
      path: '/editing'
      fullPath: '/editing'
      preLoaderRoute: typeof EditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-assistant': {
      id: '/api/ai-assistant'
      path: '/api/ai-assistant'
      fullPath: '/api/ai-assistant'
      preLoaderRoute: typeof ApiAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enquiries': {
      id: '/api/enquiries'
      path: '/api/enquiries'
      fullPath: '/api/enquiries'
      preLoaderRoute: typeof ApiEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/featured-projects': {
      id: '/api/featured-projects'
      path: '/api/featured-projects'
      fullPath: '/api/featured-projects'
      preLoaderRoute: typeof ApiFeaturedProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive': {
      id: '/api/google-drive'
      path: '/api/google-drive'
      fullPath: '/api/google-drive'
      preLoaderRoute: typeof ApiGoogleDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/homepage-content': {
      id: '/api/homepage-content'
      path: '/api/homepage-content'
      fullPath: '/api/homepage-content'
      preLoaderRoute: typeof ApiHomepageContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume': {
      id: '/api/resume'
      path: '/api/resume'
      fullPath: '/api/resume'
      preLoaderRoute: typeof ApiResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo-settings': {
      id: '/api/seo-settings'
      path: '/api/seo-settings'
      fullPath: '/api/seo-settings'
      preLoaderRoute: typeof ApiSeoSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/showreel': {
      id: '/api/showreel'
      path: '/api/showreel'
      fullPath: '/api/showreel'
      preLoaderRoute: typeof ApiShowreelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-images': {
      id: '/api/site-images'
      path: '/api/site-images'
      fullPath: '/api/site-images'
      preLoaderRoute: typeof ApiSiteImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social-links': {
      id: '/api/social-links'
      path: '/api/social-links'
      fullPath: '/api/social-links'
      preLoaderRoute: typeof ApiSocialLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verify': {
      id: '/api/admin/verify'
      path: '/api/admin/verify'
      fullPath: '/api/admin/verify'
      preLoaderRoute: typeof ApiAdminVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/': {
      id: '/api/projects/'
      path: '/api/projects'
      fullPath: '/api/projects/'
      preLoaderRoute: typeof ApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/api/projects/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  EditingRoute: EditingRoute,
  ApiAiAssistantRoute: ApiAiAssistantRoute,
  ApiCommentsRoute: ApiCommentsRoute,
  ApiEnquiriesRoute: ApiEnquiriesRoute,
  ApiFeaturedProjectsRoute: ApiFeaturedProjectsRoute,
  ApiGoogleDriveRoute: ApiGoogleDriveRoute,
  ApiHomepageContentRoute: ApiHomepageContentRoute,
  ApiResumeRoute: ApiResumeRoute,
  ApiSeoSettingsRoute: ApiSeoSettingsRoute,
  ApiShowreelRoute: ApiShowreelRoute,
  ApiSiteImagesRoute: ApiSiteImagesRoute,
  ApiSocialLinksRoute: ApiSocialLinksRoute,
  ApiUploadRoute: ApiUploadRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminVerifyRoute: ApiAdminVerifyRoute,
  ApiProjectsIdRoute: ApiProjectsIdRoute,
  ApiProjectsIndexRoute: ApiProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
